# Adressen für Abfrage vorbereiten
Quelle: https://data.geo.admin.ch/ch.bfs.gebaeude_wohnungs_register/CSV/meta.txt
Vorgehen:
- Importieren der csv-Files und alle zusammenfügen.
- Splitten und wieder zusammenfügen, sodass in einem Feld Strasse, Nummer und Ort einzeln aufgeführt sind.
- Das HR verlangt folgendes Format: "Strasse Nummer, Ort"
- Dataframe soll beinhalten: Gesamte Adresse, Ort, "Strasse Nummer, Ort", Koordinaten.

In [1]:
import pandas as pd

In [4]:
# Datensätze importieren
df1=pd.read_csv("Datensätze Adressen/1701.csv",sep=';')
df2=pd.read_csv("Datensätze Adressen/1702.csv",sep=';')
df3=pd.read_csv("Datensätze Adressen/1703.csv",sep=';')
df4=pd.read_csv("Datensätze Adressen/1704.csv",sep=';')
df5=pd.read_csv("Datensätze Adressen/1705.csv",sep=';')
df6=pd.read_csv("Datensätze Adressen/1706.csv",sep=';')
df7=pd.read_csv("Datensätze Adressen/1707.csv",sep=';')
df8=pd.read_csv("Datensätze Adressen/1708.csv",sep=';')
df9=pd.read_csv("Datensätze Adressen/1709.csv",sep=';')
df10=pd.read_csv("Datensätze Adressen/1710.csv",sep=';')
df11=pd.read_csv("Datensätze Adressen/1711.csv",sep=';')

In [5]:
dff=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11]) # Hier füge ich alle zu einem Dataframe zusammen

# Rohliste aller Gemeinden
- Grundlage: https://data.geo.admin.ch/ch.bfs.gebaeude_wohnungs_register/CSV/meta.txt
- Hier Infos zu den verschiedenen Kürzel/Bezeichnungen der Spalten https://www.housing-stat.ch/de/benutzerhilfen/41.html
- Hier finde ich die Koordinaten zu den Adressen: https://data.geo.admin.ch/ch.bfs.gebaeude_wohnungs_register/CSV/meta.txt

In [6]:
dff

,EGID,EDID,GDEKT,GDENR,GDENAME,STRNAME,DEINR,PLZ4,PLZZ,PLZNAME,GKODE,GKODN,STRSP
0,310003,0,ZG,1701,Baar,Marktgasse,12,6340,0,Baar,2682511.588,1227773.739,de
1,310004,0,ZG,1701,Baar,Marktgasse,14,6340,0,Baar,2682523.028,1227784.067,de
2,310005,0,ZG,1701,Baar,Marktgasse,16,6340,0,Baar,2682540.091,1227792.603,de
3,310006,0,ZG,1701,Baar,Marktgasse,18,6340,0,Baar,2682554.253,1227799.894,de
4,310007,0,ZG,1701,Baar,Rigistrasse,2,6340,0,Baar,2682578.674,1227789.851,de
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4885,190989130,5,ZG,1711,Zug,Gartenstadt,2a,6300,0,Zug,2681388.557,1225726.638,de
4886,320661,6,ZG,1711,Zug,Im Rötel,20g,6300,0,Zug,2682522.000,1224586.000,de
4887,320662,6,ZG,1711,Zug,Im Rötel,22g,6300,0,Zug,2682538.000,1224616.000,de
4888,320944,6,ZG,1711,Zug,Rothusweg,14g,6300,0,Zug,2681994.000,1224899.000,de
4889,320661,7,ZG,1711,Zug,Im Rötel,20h,6300,0,Zug,2682522.000,1224586.000,de

In [ ]:
# Nàchster Schritt: Zeilen so zusammennehmen, dass das Format "Strasse Nummer, Ort" entsteht.
# Gemeindename soll aber auch einzeln noch drin bleiben.